# Generated by Django 3.2.7 on 2023-06-26 19:42

import django.core.validators
from django.db import migrations, models
import exam_web_project.core.custom_validators.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('DoNotShow', 'Do not show')], default='1', max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='files/user_images', validators=[exam_web_project.core.custom_validators.validators.validate_image_max_size]),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='email',
            field=models.EmailField(max_length=254, validators=[exam_web_project.core.custom_validators.validators.validate_email]),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), exam_web_project.core.custom_validators.validators.validate_letters_only]),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='last_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), exam_web_project.core.custom_validators.validators.validate_letters_only]),
        ),
    ]
