# Generated by Django 4.2.3 on 2023-07-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20230626_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='gender',
            field=models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE'), ('Do Not Show', 'DO_NOT_SHOW')], default='Do Not Show', max_length=11),
        ),
    ]
