# Generated by Django 4.2 on 2023-07-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('PUBLISH', 'Publish'), ('DRAFT', 'Draft')], max_length=7)),
                ('email', models.ManyToManyField(to='newsletter.newsletteruser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
