# Generated by Django 4.2.3 on 2023-07-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_rename_body_newsletter_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='status',
            field=models.CharField(choices=[('Publish', 'PUBLISH'), ('Draft', 'DRAFT')], max_length=7),
        ),
    ]
