# Generated by Django 3.2.7 on 2023-06-20 18:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(2)])),
                ('slug', models.CharField(max_length=40, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('price', models.FloatField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('discount', models.IntegerField(null=True)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(null=True, upload_to='files/thumbnails')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
